mysql:
  hostname: localhost
  port: 3306
  username: username
  password: default
  database: awesome_possum
  encoding: utf8mb4

# if MYSQL2POSTGRES_ENV and RAILS_ENV is missing, development is used!
destinations:
  production:
    # adapter: default is postgresql
    adapter: postgresql
    encoding: utf8
    pool: 4
    username: terrapotamus
    password: default
    host: 127.0.0.1
    database: awesome_possum
  development:
    encoding: utf8
    pool: 4
    username: terrapotamus
    password: default
    host: 127.0.0.1
    database: awesome_possum_dev
  test:
    encoding: utf8
    pool: 4
    username: terrapotamus
    password: default
    host: 127.0.0.1
    database: awesome_possum_test
  test2:
    # use adapter 'file', if you just want to create a sql file for postgresql
    # NOTE: PostgreSQL import is skipped
    adapter: file
    # if filename is not specified, dump file name is used
    filename: /tmp/converted.sql

tables:
  - countries
  - samples
  - universes
  - variable_groups
  - variables
  - sample_variables

# If suppress_data is true, only the schema definition will be exported/migrated, and not the data
suppress_data: false

# If suppress_ddl is true, only the data will be exported/imported, and not the schema
suppress_ddl: false

# If force_truncate is true, forces a table truncate before table loading
force_truncate: false

preserve_order: true

remove_dump_file: true

dump_file_directory: /tmp

# if true, migration is to dump file (PostgreSQL import is skipped)
# NOTE: do not use remove_dump_file: true, if you want to use converted sql file)
to_file: false

report_status:  json    # false, json, xml

# If clear_schema is true, the public schema will be recreated before conversion
# The import will fail if both clear_schema and suppress_ddl are true.
clear_schema: false
