name: Run Rubocop
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Gemfile
      run: |
        touch .enable_test

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install Ruby dependencies
      run: |
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: |
        bundle exec rubocop -S
